FROM alpine:3.19

RUN apk add --no-cache curl

ADD https://github.com/aptible/supercronic/releases/download/v0.2.33/supercronic-linux-amd64 /usr/local/bin/supercronic
RUN chmod +x /usr/local/bin/supercronic

COPY crontab.cron /crontab

CMD ["/usr/local/bin/supercronic", "/crontab"]
