-- Baseline: registra todas as migrations existentes como já aplicadas
-- Rode este script UMA VEZ no banco de produção via psql ou terminal SQL do EasyPanel
-- Depois disso, `prisma migrate deploy` vai funcionar normalmente

CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  checksum VARCHAR(64) NOT NULL,
  finished_at TIMESTAMPTZ,
  migration_name VARCHAR(255) NOT NULL,
  logs TEXT,
  rolled_back_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  applied_steps_count INTEGER NOT NULL DEFAULT 0
);

INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20251228153553_add_organization', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20251228185002_add_stripe_fields', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20251228234538_add_user_role', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20251229143728_add_org_role', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20251230152415_add_invite_system', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20251230153812_deal_v2_features', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260101180309_add_email_automation_settings', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260102124347_add_multiple_pipelines', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260105182116_add_analytics_models', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260105230854_add_performance_indexes', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260108143526_add_public_api_models', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260108175339_migrate_stripe_to_mercadopago', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260108221108_add_integrations_foundation', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260109155710_add_push_subscriptions', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260109173249_add_pwa_metrics', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260109201236_add_notification_preferences', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260114182358_add_agi_tables', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260124123145_add_password_reset_token', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260125002032_add_notifications', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260126010000_add_onboarding_progress', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260131105737_add_conversation_memory', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260202175446_add_ab_testing_models', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260205110000_add_v2_modular_plans', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260206170213_add_pinned_archived_to_chat_conversation', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260206190000_add_message_reactions', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260206220000_add_contact_profile_pic', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260211135400_fase_13_analytics_deal_status', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260320000000_add_deal_closings', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260323000000_add_products', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260328000000_add_agent_actions', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260331000000_unique_message_id', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260410000000_add_task_visibility', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260427000000_add_support_tickets', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260427000000_add_waba_grandfathered', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260427100000_facebook_lead_ads_webhook', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260427200000_add_task_attachments', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260427300000_add_access_session_pageviewlog', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260428000000_add_trial_and_referral_rewards', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260429000000_facebook_oauth_flow', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260430000000_omie_integration', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260501000000_add_instagram_organization_scope', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260502000000_instagram_scheduler_v2', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260502000001_instagram_oauth', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260502100000_add_missing_deal_fields', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260504000001_add_rag_knowledge_base', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260504000002_knowledge_agent_ids', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260508000001_add_pipeline_stage_type', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260512000001_estetica_domain', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260514000001_add_user_signup_fields', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260526000001_lgpd_audit', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count) VALUES (gen_random_uuid(), 'baseline', now(), '20260609000001_convenios', NULL, NULL, now(), 1) ON CONFLICT (migration_name) DO NOTHING;
