import {
  siMailchimp,
  siBrevo,
  siNotion,
  siTrello,
  siAsana,
  siTypeform,
  siZoom,
  siTelegram,
  siStripe,
  siMercadopago,
  siZapier,
  siTiktok,
  siViber,
  siWhatsapp,
  siInstagram,
  siMeta,
  siApple,
  siN8n,
  siMake,
} from 'simple-icons'
import type { IntegrationIconDef } from './integration-icon'

export type IntegrationCategory =
  | 'mensageria'
  | 'telefonia'
  | 'calendarios'
  | 'email-marketing'
  | 'anuncios'
  | 'pagamentos'
  | 'nfse'
  | 'convenios'
  | 'telemedicina'
  | 'erp'
  | 'produtividade'
  | 'webhooks'
  | 'validacoes'

export interface IntegrationMeta {
  id: string
  name: string
  shortDescription: string
  category: IntegrationCategory
  icon: IntegrationIconDef
  cardBgColor: string
  href: string
  requiresTier?: 'BUSINESS' | 'PRO'
  selfHostable?: boolean
  docsUrl?: string
  status?: 'stable' | 'beta' | 'maintenance' | 'soon'
  costNote?: string
  isBrazilian?: boolean
  useCase?: string
}

export const CATEGORIES: { id: IntegrationCategory | 'todas'; label: string }[] = [
  { id: 'todas', label: 'Todas' },
  { id: 'mensageria', label: 'Mensageria' },
  { id: 'telefonia', label: 'Telefonia' },
  { id: 'calendarios', label: 'Calendários' },
  { id: 'email-marketing', label: 'E-mail & Marketing' },
  { id: 'anuncios', label: 'Anúncios' },
  { id: 'pagamentos', label: 'Pagamentos' },
  { id: 'nfse', label: 'NF-Se' },
  { id: 'convenios', label: 'Convênios & TISS' },
  { id: 'telemedicina', label: 'Telemedicina' },
  { id: 'erp', label: 'ERP & Operações' },
  { id: 'produtividade', label: 'Produtividade' },
  { id: 'webhooks', label: 'Webhooks' },
  { id: 'validacoes', label: 'Validações' },
]

function brand(si: { path: string; hex: string; title: string }): IntegrationIconDef {
  return { type: 'brand', path: si.path, hex: `#${si.hex}`, title: si.title }
}

/** SVG file from public/logos/integrations/<filename> */
function image(filename: string, hex: string, title: string, monochrome = true): IntegrationIconDef {
  return { type: 'image', src: `/logos/integrations/${filename}`, hex, title, monochrome }
}

export const INTEGRATIONS: IntegrationMeta[] = [
  // === MENSAGERIA (7) ===
  {
    id: 'whatsapp-oficial',
    name: 'WhatsApp Oficial',
    shortDescription: 'API Cloud da Meta — produção em larga escala',
    category: 'mensageria',
    icon: brand(siWhatsapp),
    cardBgColor: '#25D366',
    href: '/dashboard/settings/integrations/whatsapp-official',
    requiresTier: 'BUSINESS',
    docsUrl: 'https://developers.facebook.com/docs/whatsapp/cloud-api',
    costNote: 'Cobrança por conversa pela Meta',
  },
  {
    id: 'whatsapp-evolution',
    name: 'WhatsApp Evolution',
    shortDescription: 'API self-hosted — você hospeda sua instância',
    category: 'mensageria',
    icon: image('whatsapp-evolution.svg', '#10B981', 'WhatsApp Evolution'),
    cardBgColor: '#10B981',
    href: '/dashboard/settings/integrations/whatsapp-evolution',
    selfHostable: true,
    docsUrl: 'https://doc.evolution-api.com/',
    costNote: 'Hospedagem própria — grátis',
  },
  {
    id: 'whatsapp-zapi',
    name: 'WhatsApp Z-API',
    shortDescription: 'Provider brasileiro pago — fácil setup',
    category: 'mensageria',
    icon: image('whatsapp-zapi.svg', '#14B8A6', 'WhatsApp Z-API'),
    cardBgColor: '#14B8A6',
    href: '/dashboard/settings/integrations/whatsapp-zapi',
    docsUrl: 'https://developer.z-api.io/',
    isBrazilian: true,
    costNote: '~R$ 99/mês com Z-API',
  },
  {
    id: 'instagram-dm',
    name: 'Instagram Direct',
    shortDescription: 'Receba DMs no Chat Center',
    category: 'mensageria',
    icon: brand(siInstagram),
    cardBgColor: '#E1306C',
    href: '/dashboard/settings/integrations/instagram-dm',
    docsUrl: 'https://developers.facebook.com/docs/messenger-platform/instagram',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    shortDescription: 'Bot de notificações da clínica',
    category: 'mensageria',
    icon: brand(siTelegram),
    cardBgColor: `#${siTelegram.hex}`,
    href: '/dashboard/settings/integrations/telegram',
    docsUrl: 'https://core.telegram.org/bots',
    costNote: 'Grátis',
  },
  {
    id: 'viber',
    name: 'Viber',
    shortDescription: 'Mensagens via Viber Business',
    category: 'mensageria',
    icon: brand(siViber),
    cardBgColor: `#${siViber.hex}`,
    href: '/dashboard/settings/integrations/viber',
    status: 'soon',
  },
  {
    id: 'webchat',
    name: 'Chat no Site',
    shortDescription: 'Widget de chat para sua landing',
    category: 'mensageria',
    icon: image('webchat.svg', '#8B5CF6', 'Chat no Site'),
    cardBgColor: '#8B5CF6',
    href: '/dashboard/settings/integrations/webchat',
    status: 'soon',
  },

  // === TELEFONIA (4) ===
  {
    id: 'pabx',
    name: 'PABX',
    shortDescription: 'Intelbras, Yealink, Asterisk via webhook',
    category: 'telefonia',
    icon: image('pabx.svg', '#06B6D4', 'PABX'),
    cardBgColor: '#06B6D4',
    href: '/dashboard/settings/integrations/pabx',
    costNote: 'Sua infraestrutura',
  },
  {
    id: 'twilio-voice',
    name: 'Twilio Voice',
    shortDescription: 'Chamadas de voz programáveis',
    category: 'telefonia',
    icon: image('twilio-voice.svg', '#F22F46', 'Twilio'),
    cardBgColor: '#F22F46',
    href: '/dashboard/settings/integrations/twilio-voice',
    status: 'soon',
  },
  {
    id: 'ringcentral',
    name: 'RingCentral',
    shortDescription: 'Telefonia em nuvem corporativa',
    category: 'telefonia',
    icon: image('ringcentral.svg', '#FF6B00', 'RingCentral'),
    cardBgColor: '#FF6B00',
    href: '/dashboard/settings/integrations/ringcentral',
    status: 'soon',
  },
  {
    id: 'callgear',
    name: 'CallGear',
    shortDescription: 'Rastreamento de chamadas e analytics',
    category: 'telefonia',
    icon: image('callgear.svg', '#3B82F6', 'CallGear'),
    cardBgColor: '#3B82F6',
    href: '/dashboard/settings/integrations/callgear',
    status: 'soon',
  },

  // === CALENDÁRIOS (3) ===
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    shortDescription: 'Sincronize agendamentos com sua agenda Google',
    category: 'calendarios',
    icon: image('google-calendar.svg', '#FFFFFF', 'Google Calendar', false),
    cardBgColor: '#FFFFFF',
    href: '/dashboard/settings/integrations/google-calendar',
  },
  {
    id: 'outlook-calendar',
    name: 'Outlook Calendar',
    shortDescription: 'Sincronização com Microsoft 365',
    category: 'calendarios',
    icon: image('outlook-calendar.svg', '#FFFFFF', 'Microsoft Outlook', false),
    cardBgColor: '#FFFFFF',
    href: '/dashboard/settings/integrations/outlook-calendar',
    status: 'soon',
  },
  {
    id: 'apple-calendar',
    name: 'Apple Calendar',
    shortDescription: 'iCal — assinatura de calendário .ics',
    category: 'calendarios',
    icon: brand(siApple),
    cardBgColor: '#555555',
    href: '/dashboard/settings/integrations/apple-calendar',
    status: 'soon',
  },

  // === E-MAIL & MARKETING (6) ===
  {
    id: 'smtp',
    name: 'E-mail (SMTP)',
    shortDescription: 'Envie e-mails do seu próprio domínio',
    category: 'email-marketing',
    icon: image('smtp.svg', '#3B82F6', 'E-mail SMTP'),
    cardBgColor: '#3B82F6',
    href: '/dashboard/settings/integrations/smtp',
    costNote: 'Gmail, Outlook, SendGrid, Resend...',
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    shortDescription: 'Campanhas de e-mail e automações',
    category: 'email-marketing',
    icon: brand(siMailchimp),
    cardBgColor: `#${siMailchimp.hex}`,
    href: '/dashboard/settings/integrations/mailchimp',
    status: 'soon',
  },
  {
    id: 'brevo',
    name: 'Brevo (Sendinblue)',
    shortDescription: 'E-mail marketing + SMS + chat',
    category: 'email-marketing',
    icon: brand(siBrevo),
    cardBgColor: `#${siBrevo.hex}`,
    href: '/dashboard/settings/integrations/brevo',
    status: 'soon',
  },
  {
    id: 'activecampaign',
    name: 'ActiveCampaign',
    shortDescription: 'Automação avançada de marketing',
    category: 'email-marketing',
    icon: image('activecampaign.svg', '#356AE6', 'ActiveCampaign'),
    cardBgColor: '#356AE6',
    href: '/dashboard/settings/integrations/activecampaign',
    status: 'soon',
  },
  {
    id: 'mailerlite',
    name: 'MailerLite',
    shortDescription: 'E-mail marketing simples',
    category: 'email-marketing',
    icon: image('mailerlite.svg', '#09C269', 'MailerLite'),
    cardBgColor: '#09C269',
    href: '/dashboard/settings/integrations/mailerlite',
    status: 'soon',
  },
  {
    id: 'rd-station',
    name: 'RD Station',
    shortDescription: 'Automação de marketing brasileira',
    category: 'email-marketing',
    icon: image('rd-station.svg', '#19B4FE', 'RD Station'),
    cardBgColor: '#19B4FE',
    href: '/dashboard/settings/integrations/rd-station',
    isBrazilian: true,
    status: 'soon',
  },

  // === ANÚNCIOS (5) ===
  {
    id: 'google-ads',
    name: 'Google Ads',
    shortDescription: 'CAC real e ROI de campanhas',
    category: 'anuncios',
    icon: image('google-ads.svg', '#FFFFFF', 'Google Ads', false),
    cardBgColor: '#FFFFFF',
    href: '/dashboard/settings/integrations/google-ads',
  },
  {
    id: 'facebook-ads',
    name: 'Meta Ads',
    shortDescription: 'Facebook e Instagram Ads — atribuição',
    category: 'anuncios',
    icon: brand(siMeta),
    cardBgColor: '#1877F2',
    href: '/dashboard/settings/integrations/facebook-ads',
  },
  {
    id: 'instagram-posts',
    name: 'Instagram (Posts)',
    shortDescription: 'Agendador de publicações',
    category: 'anuncios',
    icon: brand(siInstagram),
    cardBgColor: '#C13584',
    href: '/dashboard/settings/integrations/instagram',
  },
  {
    id: 'tiktok-ads',
    name: 'TikTok Ads',
    shortDescription: 'Atribuição de campanhas TikTok',
    category: 'anuncios',
    icon: brand(siTiktok),
    cardBgColor: `#${siTiktok.hex}`,
    href: '/dashboard/settings/integrations/tiktok-ads',
    status: 'soon',
  },
  {
    id: 'linkedin-ads',
    name: 'LinkedIn Ads',
    shortDescription: 'Campanhas B2B no LinkedIn',
    category: 'anuncios',
    icon: image('linkedin-ads.svg', '#0A66C2', 'LinkedIn'),
    cardBgColor: '#0A66C2',
    href: '/dashboard/settings/integrations/linkedin-ads',
    status: 'soon',
  },

  // === PAGAMENTOS (5) ===
  {
    id: 'asaas',
    name: 'Asaas',
    shortDescription: 'PIX, boleto, cartão e recorrência',
    category: 'pagamentos',
    icon: image('asaas.svg', '#0F4C9A', 'Asaas'),
    cardBgColor: '#0F4C9A',
    href: '/dashboard/settings/integrations/asaas',
    docsUrl: 'https://docs.asaas.com/',
    isBrazilian: true,
    useCase: 'Cobrança recorrente PIX/Boleto',
  },
  {
    id: 'mercadopago-checkout',
    name: 'MercadoPago Checkout',
    shortDescription: 'Receba pagamentos dos seus pacientes',
    category: 'pagamentos',
    icon: brand(siMercadopago),
    cardBgColor: '#00B1EA',
    href: '/dashboard/settings/integrations/mercadopago-checkout',
    docsUrl: 'https://www.mercadopago.com.br/developers/pt',
    isBrazilian: true,
  },
  {
    id: 'pagseguro',
    name: 'PagSeguro',
    shortDescription: 'Checkout e cobrança PagBank',
    category: 'pagamentos',
    icon: image('pagseguro.svg', '#FFC107', 'PagSeguro'),
    cardBgColor: '#FFC107',
    href: '/dashboard/settings/integrations/pagseguro',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'pagarme',
    name: 'Pagar.me',
    shortDescription: 'Gateway de pagamento da Stone',
    category: 'pagamentos',
    icon: image('pagarme.svg', '#65A300', 'Pagar.me'),
    cardBgColor: '#65A300',
    href: '/dashboard/settings/integrations/pagarme',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    shortDescription: 'Pagamentos internacionais',
    category: 'pagamentos',
    icon: brand(siStripe),
    cardBgColor: `#${siStripe.hex}`,
    href: '/dashboard/settings/integrations/stripe',
    status: 'soon',
  },

  // === NF-Se (4) ===
  {
    id: 'focus-nfe',
    name: 'Focus NFe',
    shortDescription: 'Emissão automática de NF-Se',
    category: 'nfse',
    icon: image('focus-nfe.svg', '#F59E0B', 'Focus NFe'),
    cardBgColor: '#F59E0B',
    href: '/dashboard/settings/integrations/focus-nfe',
    docsUrl: 'https://focusnfe.com.br/doc/',
    isBrazilian: true,
  },
  {
    id: 'enotas',
    name: 'eNotas',
    shortDescription: 'API de emissão de nota fiscal',
    category: 'nfse',
    icon: image('enotas.svg', '#7C3AED', 'eNotas'),
    cardBgColor: '#7C3AED',
    href: '/dashboard/settings/integrations/enotas',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'nfeio',
    name: 'NFE.io',
    shortDescription: 'Emissão de NF-Se em nuvem',
    category: 'nfse',
    icon: image('nfeio.svg', '#6366F1', 'NFE.io'),
    cardBgColor: '#6366F1',
    href: '/dashboard/settings/integrations/nfeio',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'plugnotas',
    name: 'Plug.notas',
    shortDescription: 'Plataforma fiscal multi-município',
    category: 'nfse',
    icon: image('plugnotas.svg', '#0EA5E9', 'Plug.notas'),
    cardBgColor: '#0EA5E9',
    href: '/dashboard/settings/integrations/plugnotas',
    isBrazilian: true,
    status: 'soon',
  },

  // === CONVÊNIOS & TISS (5) ===
  {
    id: 'unimed',
    name: 'Unimed',
    shortDescription: 'Envio de guias TISS via API',
    category: 'convenios',
    icon: image('unimed.svg', '#00995D', 'Unimed'),
    cardBgColor: '#00995D',
    href: '/dashboard/settings/integrations/unimed',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'amil',
    name: 'Amil',
    shortDescription: 'Autorização e faturamento Amil',
    category: 'convenios',
    icon: image('amil.svg', '#005CAB', 'Amil'),
    cardBgColor: '#005CAB',
    href: '/dashboard/settings/integrations/amil',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'bradesco-saude',
    name: 'Bradesco Saúde',
    shortDescription: 'Elegibilidade e guias Bradesco',
    category: 'convenios',
    icon: image('bradesco-saude.svg', '#CC092F', 'Bradesco Saúde'),
    cardBgColor: '#CC092F',
    href: '/dashboard/settings/integrations/bradesco-saude',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'medtiss',
    name: 'MEDTISS',
    shortDescription: 'Plataforma TISS unificada',
    category: 'convenios',
    icon: image('medtiss.svg', '#10B981', 'MEDTISS'),
    cardBgColor: '#10B981',
    href: '/dashboard/settings/integrations/medtiss',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'hapvida',
    name: 'Hapvida',
    shortDescription: 'Integração TISS Hapvida NotreDame',
    category: 'convenios',
    icon: image('hapvida.svg', '#F97316', 'Hapvida'),
    cardBgColor: '#F97316',
    href: '/dashboard/settings/integrations/hapvida',
    isBrazilian: true,
    status: 'soon',
  },

  // === TELEMEDICINA (4) ===
  {
    id: 'doctoralia',
    name: 'Doctoralia',
    shortDescription: 'Agendamento online e perfil público',
    category: 'telemedicina',
    icon: image('doctoralia.svg', '#0BA9D5', 'Doctoralia'),
    cardBgColor: '#0BA9D5',
    href: '/dashboard/settings/integrations/doctoralia',
    status: 'soon',
  },
  {
    id: 'conexa',
    name: 'Conexa Saúde',
    shortDescription: 'Plataforma de telemedicina',
    category: 'telemedicina',
    icon: image('conexa.svg', '#7C3AED', 'Conexa Saúde'),
    cardBgColor: '#7C3AED',
    href: '/dashboard/settings/integrations/conexa',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'memed',
    name: 'Memed',
    shortDescription: 'Prescrição digital válida',
    category: 'telemedicina',
    icon: image('memed.svg', '#EC4899', 'Memed'),
    cardBgColor: '#EC4899',
    href: '/dashboard/settings/integrations/memed',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'whitebook',
    name: 'Whitebook',
    shortDescription: 'Decisão clínica e protocolos',
    category: 'telemedicina',
    icon: image('whitebook.svg', '#3B82F6', 'Whitebook'),
    cardBgColor: '#3B82F6',
    href: '/dashboard/settings/integrations/whitebook',
    isBrazilian: true,
    status: 'soon',
  },

  // === ERP & OPERAÇÕES (3) ===
  {
    id: 'omie',
    name: 'Omie ERP',
    shortDescription: 'Sincronize clientes, pedidos e financeiro',
    category: 'erp',
    icon: image('omie.svg', '#FF6B35', 'Omie ERP'),
    cardBgColor: '#FF6B35',
    href: '/dashboard/settings/integrations/omie',
    docsUrl: 'https://app.omie.com.br/api/v1/',
    isBrazilian: true,
  },
  {
    id: 'contaazul',
    name: 'ContaAzul',
    shortDescription: 'Gestão financeira e contábil',
    category: 'erp',
    icon: image('contaazul.svg', '#06B6D4', 'ContaAzul'),
    cardBgColor: '#06B6D4',
    href: '/dashboard/settings/integrations/contaazul',
    isBrazilian: true,
    status: 'soon',
  },
  {
    id: 'bling',
    name: 'Bling',
    shortDescription: 'ERP completo para PMEs',
    category: 'erp',
    icon: image('bling.svg', '#005FFF', 'Bling'),
    cardBgColor: '#005FFF',
    href: '/dashboard/settings/integrations/bling',
    isBrazilian: true,
    status: 'soon',
  },

  // === PRODUTIVIDADE & FORMS (8) ===
  {
    id: 'zoom',
    name: 'Zoom',
    shortDescription: 'Reuniões e tele-consulta',
    category: 'produtividade',
    icon: brand(siZoom),
    cardBgColor: `#${siZoom.hex}`,
    href: '/dashboard/settings/integrations/zoom',
    docsUrl: 'https://developers.zoom.us/',
  },
  {
    id: 'slack',
    name: 'Slack',
    shortDescription: 'Notificações da clínica no Slack',
    category: 'produtividade',
    icon: image('slack.svg', '#FFFFFF', 'Slack', false),
    cardBgColor: '#FFFFFF',
    href: '/dashboard/settings/integrations/slack',
    status: 'soon',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    shortDescription: 'Reuniões e notificações Teams',
    category: 'produtividade',
    icon: image('teams.svg', '#FFFFFF', 'Microsoft Teams', false),
    cardBgColor: '#FFFFFF',
    href: '/dashboard/settings/integrations/teams',
    status: 'soon',
  },
  {
    id: 'notion',
    name: 'Notion',
    shortDescription: 'Sincronize pacientes com Notion',
    category: 'produtividade',
    icon: brand(siNotion),
    cardBgColor: `#${siNotion.hex}`,
    href: '/dashboard/settings/integrations/notion',
    status: 'soon',
  },
  {
    id: 'trello',
    name: 'Trello',
    shortDescription: 'Kanban de procedimentos no Trello',
    category: 'produtividade',
    icon: brand(siTrello),
    cardBgColor: `#${siTrello.hex}`,
    href: '/dashboard/settings/integrations/trello',
    status: 'soon',
  },
  {
    id: 'asana',
    name: 'Asana',
    shortDescription: 'Gestão de projetos da clínica',
    category: 'produtividade',
    icon: brand(siAsana),
    cardBgColor: `#${siAsana.hex}`,
    href: '/dashboard/settings/integrations/asana',
    status: 'soon',
  },
  {
    id: 'typeform',
    name: 'Typeform',
    shortDescription: 'Ficha de anamnese e pesquisas',
    category: 'produtividade',
    icon: brand(siTypeform),
    cardBgColor: `#${siTypeform.hex}`,
    href: '/dashboard/settings/integrations/typeform',
    status: 'soon',
  },
  {
    id: 'jotform',
    name: 'JotForm',
    shortDescription: 'Formulários online e captação',
    category: 'produtividade',
    icon: image('jotform.svg', '#FF6100', 'JotForm'),
    cardBgColor: '#FF6100',
    href: '/dashboard/settings/integrations/jotform',
    status: 'soon',
  },

  // === WEBHOOKS & AUTOMAÇÃO (4) ===
  {
    id: 'n8n',
    name: 'N8N',
    shortDescription: 'Automação de workflows visuais',
    category: 'webhooks',
    icon: brand(siN8n),
    cardBgColor: '#EA4B71',
    href: '/dashboard/settings/integrations/n8n',
    docsUrl: 'https://docs.n8n.io/',
  },
  {
    id: 'webhook-generic',
    name: 'Webhook Genérico',
    shortDescription: 'Integre com qualquer ferramenta',
    category: 'webhooks',
    icon: image('webhook-generic.svg', '#8B5CF6', 'Webhook'),
    cardBgColor: '#8B5CF6',
    href: '/dashboard/settings/integrations/webhook-generic',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    shortDescription: 'Conecte com 5000+ apps',
    category: 'webhooks',
    icon: brand(siZapier),
    cardBgColor: `#${siZapier.hex}`,
    href: '/dashboard/settings/integrations/zapier',
    status: 'soon',
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    shortDescription: 'Automações visuais avançadas',
    category: 'webhooks',
    icon: brand(siMake),
    cardBgColor: '#6D00CC',
    href: '/dashboard/settings/integrations/make',
    status: 'soon',
  },

  // === VALIDAÇÕES (1) ===
  {
    id: 'cfm-validator',
    name: 'CFM / Conselhos',
    shortDescription: 'Valide automaticamente CRM, CRO e demais',
    category: 'validacoes',
    icon: image('cfm-validator.svg', '#10B981', 'CFM'),
    cardBgColor: '#10B981',
    href: '/dashboard/settings/team',
    isBrazilian: true,
  },
]
