export const BENTO_ITEMS = [
  {
    id: 'kanban',
    title: 'Kanban Clínico',
    description: 'Visualize cada paciente em seu estágio de tratamento. Arraste, priorize, nunca perca um follow-up.',
    icon: '⬛',
    accent: '#C5A059',
    size: 'large' as const,
    tag: 'Organização',
  },
  {
    id: 'ai-triage',
    title: 'Triagem com IA',
    description: 'A IA classifica a urgência e sugere o próximo passo antes de você abrir o prontuário.',
    icon: '◈',
    accent: '#489FB5',
    size: 'small' as const,
    tag: 'Inteligência',
  },
  {
    id: 'analytics',
    title: 'Analytics em tempo real',
    description: 'LTV, churn, taxa de retorno — dashboards que revelam o que realmente impacta sua receita.',
    icon: '◉',
    accent: '#C5A059',
    size: 'small' as const,
    tag: 'Crescimento',
  },
  {
    id: 'email',
    title: 'Automações de Email',
    description: 'Sequências personalizadas que reengajam pacientes no momento certo, com a mensagem certa.',
    icon: '▣',
    accent: '#489FB5',
    size: 'small' as const,
    tag: 'Retenção',
  },
  {
    id: 'calendar',
    title: 'Agenda Inteligente',
    description: 'Agendamento online com confirmação automática. Sem ligações, sem faltas.',
    icon: '◫',
    accent: '#C5A059',
    size: 'small' as const,
    tag: 'Eficiência',
  },
  {
    id: 'payments',
    title: 'Pagamentos integrados',
    description: 'Link de cobrança, parcelamento e conciliação financeira — tudo dentro do CRM.',
    icon: '◆',
    accent: '#489FB5',
    size: 'small' as const,
    tag: 'Financeiro',
  },
]
