-- Migration: Add new IntegrationType enum values for test/route.ts logging
-- Run on production: psql $DATABASE_URL -f this_file.sql

ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'VIBER';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'WEBCHAT';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'TWILIO_VOICE';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'RINGCENTRAL';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'CALLGEAR';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'ENOTAS';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'NFEIO';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'PLUGNOTAS';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'UNIMED';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'AMIL';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'BRADESCO_SAUDE';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'MEDTISS';
ALTER TYPE "IntegrationType" ADD VALUE IF NOT EXISTS 'HAPVIDA';
